@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package dev.hail.confluence_anvil_craft.block;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;